---
exporter_versions:
  node_exporter: 1.1.2

node_exporter:
  binary_url: >
    https://github.com/prometheus/node_exporter/releases/download/v
    {{ exporter_versions.node_exporter }}/node_exporter-
    {{ exporter_versions.node_exporter }}.linux-amd64.tar.gz"
  install_dir: "/usr/bin/node_exporter"
  service_config_file: "/etc/systemd/system/node_exporter.service"
  web_config_file: /usr/bin/node_exporter/web.yml
  port: 9100
  ssl_key_file: "/usr/bin/node_exporter/node_exporter.key"
  ssl_cert_file: "/usr/bin/node_exporter/node_exporter.crt"
