---
xnat_container_service:
  host: ""
  ip: ""
  port: ""
  cert_dir: "/home/docker/.docker"
  client_cert_dir: "/home/docker/.docker/client_certs"
  ca_key: "/home/docker/.docker/ca.key"
  ca_csr: "/home/docker/.docker/ca.csr"
  ca_cert: "/home/docker/.docker/ca.pem"
  server_key: "/home/docker/.docker/server-key.pem"
  server_csr: "/home/docker/.docker/server.csr"
  server_cert: "/home/docker/.docker/server-cert.pem"

docker:
  owner: "root"
  group: "root"
  config_dir: "/etc/docker"
  daemon_conf_file: "/etc/docker/daemon.json"
  service_file_dir: "/etc/systemd/system/docker.service.d"
  service_name: "docker"
