---
- name: Prepare
  hosts: instance
  become: true
  gather_facts: true
  roles:
    - role: mirsg.install_python
      vars:
        install_python:
          version: "3"
          pip_version: "21.2.4"
          pip_executable: "pip3"
          system_packages:
            - python3
            - python3-pip
            - python3-setuptools
          pip_packages:
            - cryptography
