---
- name: Prepare
  hosts: instance
  become: true
  gather_facts: true
  roles:
    - role: mirsg.install_python
      vars:
        install_python:
          version: "2"
          pip_version: "20.3.4"
          pip_executable: "pip"
          system_packages:
            - python
            - python-pip
            - python-setuptools
          pip_packages:
            - cryptography
