---
all:
  # List of all servers, defining their alias and IP (ansible_host)
  hosts:
    vagrant_xnat_web:
      ansible_host: web.xnat.local
      ansible_ip: 192.168.56.10
      ansible_port: 22
    vagrant_xnat_db:
      ansible_host: db.xnat.local
      ansible_ip: 192.168.56.11
      ansible_port: 22
    vagrant_xnat_cserv:
      ansible_host: cserv.xnat.local
      ansible_ip: 192.168.56.14
      ansible_port: 22
    mirsg_dev_xnat_web:
      ansible_host: mirsg-dev.cs.ucl.ac.uk
      harvester_cluster_base_ip: 10.52.0.0
      harvester_cluster_subnet_mask: 255.255.255.0
      ansible_ssh_ip: 10.53.105.12
      ansible_ssh_port: 30201
    mirsg_dev_xnat_db:
      ansible_host: mirsg-dev.cs.ucl.ac.uk
      ansible_ssh_ip: 10.53.55.32
      ansible_ssh_port: 30204
      harvester_pg_svc: dev-xnat-db-pg

  # Groups that hosts belong to
  children:
    # The primary group of xnat servers
    vagrant_xnat:
      hosts:
        vagrant_xnat_web:
        vagrant_xnat_db:
        vagrant_xnat_cserv:

    mirsg_dev_xnat:
      hosts:
        mirsg_dev_xnat_web:
        mirsg_dev_xnat_db:

    # All postgres servers
    db:
      hosts:
        vagrant_xnat_db:
        mirsg_dev_xnat_db:

    # All the web (XNAT/Tomcat) servers
    web:
      hosts:
        vagrant_xnat_web:
        mirsg_dev_xnat_web:

    # All the container service (docker) servers
    container_service_host:
      hosts:
        vagrant_xnat_cserv:

    # A group of the cserv container service and all the web servers it serves
    cserv:
      hosts:
        vagrant_xnat_cserv:
        vagrant_xnat_web:

    common:
      hosts:
        vagrant_xnat_cserv:
        vagrant_xnat_web:
        vagrant_xnat_db:
        mirsg_dev_xnat_web:
        mirsg_dev_xnat_db:

    monitoring_server:
      hosts:
        vagrant_xnat_cserv:

    monitoring_service:
      hosts:
        vagrant_xnat_cserv:
        vagrant_xnat_web:
        vagrant_xnat_db:
