---
- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure internal zone is open to ssh
  ansible.posix.firewalld:
    zone: internal
    service: ssh
    immediate: true
    permanent: true
    state: enabled

- name: Ensure no samba-client for internal zone
  ansible.posix.firewalld:
    zone: internal
    service: samba-client
    immediate: true
    permanent: true
    state: disabled

- name: Add sources to internal zone
  ansible.posix.firewalld:
    zone: internal
    source: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ internal_networks }}"

- name: Open internal docker port to XNAT servers
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 source address={{ item }}/32 port protocol=tcp port={{ xnat_container_service.port }} accept"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ host_ips }}"

- name: Ensure public zone is not open to ssh
  ansible.posix.firewalld:
    zone: public
    service: ssh
    immediate: true
    permanent: true
    state: disabled

- name: Check firewall default zone
  ansible.builtin.shell: |
    set -o pipefail
    firewall-cmd --get-default-zone | grep -i drop
  register: firewall_db_default_zone
  changed_when: false
  failed_when: false

- name: Drop all default connections
  ansible.builtin.command: firewall-cmd --set-default-zone=drop
  when: firewall_db_default_zone.rc != 0
  changed_when: false
