---
- name: Update container service TLS
  hosts: container_service_host
  become: true
  gather_facts: true

  roles:
    - {
      role: sign_docker_client_cert,
      hosts: "{{ xnat_container_service.clients }}",
    }
