name: checks

on: [push, pull_request]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache stuff
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            ~/.ansible/collections/ansible_collections
            ~/.cache/pre-commit
          key: >
            cache-${{ env.PY }}-
            ${{ hashFiles('.pre-commit-config.yaml') }}-
            ${{ hashFiles('ansible/playbooks/roles/requirements.yml') }}

      - name: Install dependencies
        run: pip install ansible pre-commit

      - name: Install the infrastructure collection
        run: ansible-galaxy collection install . --force

      - name: Install pre-commit hooks
        run: pre-commit install

      # This will run on all files in the repo not just those that have been
      # committed. Once formatting has been applied once globally, from then on
      # the files being changed by pre-commit should be just those that are
      # being committed - provided that people are using the pre-commit hook to
      # format their code.
      - name: Run pre-commit
        run: pre-commit run --all-files --color always
