name: "mirsg.infrastructure.docker"
on:
  push:
    paths:
      - 'roles/docker/**'
      - '.github/workflows/docker-molecule.yml'
  pull_request:
    paths:
      - 'roles/docker/**'
      - '.github/workflows/docker-molecule.yml'

jobs:
  molecule:
    uses: ./.github/workflows/run-molecule-test.yml
