name: "mirsg.infrastructure.docker"
on:
  push:
    paths:
      - 'roles/docker/**'
      - '.github/workflows/docker-molecule.yml'
  pull_request:
    paths:
      - 'roles/docker/**'
      - '.github/workflows/docker-molecule.yml'

jobs:
  molecule:
    strategy:
      fail-fast: true
      matrix:
        molecule_scenario:
          - centos7
          - rocky8
    uses: ./.github/workflows/run-molecule-test.yml
    with:
      role: "docker"
      scenario: ${{ matrix.molecule_scenario }}
