name: Run molecule tests

on:
  workflow_call:
    inputs:
      role:
        required: true
        type: string
      scenario:
        required: true
        type: string

jobs:
  molecule:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install rsync
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible ansible-lint molecule molecule-plugins[docker] docker requests==2.29.0

      - name: Install role dependencies
        run: |
          ansible-galaxy install -r roles/requirements.yml

      - name: Install the collection
        run: |
          ansible-galaxy collection install . --force

      - name: Run role tests
        run: >-
          cd roles/${{ inputs.role }} &&
          molecule --version &&
          ansible --version &&
          molecule --debug test -s ${{ inputs.scenario }}
